### ISSUE TITLE
Push-to-talk key Overlap?

### ISSUE THREAD

**Issue by baykovr** [baykovr/AVPI#12]
Current implementation of action sequence + settings does not check if a profile calls the push to talk key, allowing the profile to invoke push to talk on it's own.

Not sure if this is a feature or a bug, since this allows the profile to prompt the user for voice input (via push to talk invocation)

**Comment by Pazns** [comment]
The only case I can see is when the profile performs its own extinction.
I'm not sure if this is a feature, but surely it doesn't seem to be a bug.
