### ISSUE TITLE
Assuming commands

### ISSUE THREAD

**Issue by Arthmael8610** [baykovr/AVPI#14]
it works great if you don't say anything at all while you are playing lol but as i stream i am constantly talking so it assumes what command i say no matter what i say and it just keeps randomly choosing commands to run, if you can make it so it does not assume it would be great!

**Comment by cptmashek** [comment]
I think he means "assume" as in, the program should have an activation keyword. From what I understood, given that he streams and talks, AVPI is trying to parse *all* of his conversation as commands.

**Comment by baykovr** [comment]
As in, the "ok google" route?

**Comment by cptmashek** [comment]
Yeah, in the vein of Google Now, Siri, etc. That is something I am going to require as well if I use this. Checking out the code now. :)

**Comment by jkenters** [comment]
I just added "computer" before everything. Works for now :-)

**Comment by baykovr** [comment]
It wouldn't be difficult to add a "keyword" feature, thing is there is a lot to do presently. I'll put it on my feature creep list.

**Comment by baykovr** [comment]
With the addition of push to talk you now have a reliable way to keep gavpi from being over zealous.
