### ISSUE TITLE
MS Windows Display Scaling - broken gui

### ISSUE THREAD

**Issue by rpr13** [baykovr/AVPI#17]
Hi.
I've found an issue with scaling the gui of GAVPI in Windows 8.1 Pro x64.
I've had scale set to 125%. Profile Modify has been broken, forms are "hidden".
Setting advanced options: "Disable DPI scaling" doesn't change anything.

**Comment by baykovr** [comment]
Added DPI scaling context awareness to fix issue.

https://github.com/baykovr/AVPI/commit/5511404aa596b1a54740c1988f57c902e53184ac

Let me know if the problem persist, its also possible to force it to stay at a lower DPI which will make it look blurry (but fully functional)

**Comment by baykovr** [comment]
Should be fixed but untested, reopen if persists.
