### ISSUE TITLE
Gavpi 0.04 Alpha - Can not change voice from defoult windows voice " microsoft anna"

### ISSUE THREAD

**Issue by TheTruelycon** [baykovr/AVPI#18]
Summary: When user change voice from microsoft anna to ( in my case Amy 1.6.3 Ivona speech) and click save changes are not saved.  

Steps to reproduce:
1) Launch Gavpi 0.04
2) Enter settings
3) Chnage speech synthesizer
4) Click save
5) Go settings again

Actual result: The changes were not saved

Expected result: Changes should be save properly

I am running win 7 HP 64 bit

**Comment by baykovr** [comment]
Thanks for the report,

Fixed in https://github.com/baykovr/AVPI/commit/91b0633929d82ffa6e1699ddf75a5bd51fd425f4

I'll try to get a release pushed out this week which will have this included.

**Comment by baykovr** [comment]
Further fix:

https://github.com/baykovr/AVPI/commit/eeb64481d52ac6ac1e5faa9a8308656fa4b2ce26

(forgot to actually update the selection items, oops)

**Comment by TheTruelycon** [comment]
I would like to test GAVPI more but I still can not change the voice from microsoft anna so I can not use it:(

**Comment by baykovr** [comment]
Right, it's fixed just haven't put out a release yet. 

I'll compile a version for you tomorrow so you can test, do you have an email address I can send to? (I don't want to post the recent version publicly yet)

**Comment by TheTruelycon** [comment]
lyconnn@gmail.com Thank You!
