### ISSUE TITLE
Paste String from Clipboard

### ISSUE THREAD

**Issue by Bandoth** [baykovr/AVPI#20]
As a Commander in Elite: Dangerous, I would like the ability to store predefined strings in the profile that can be directly pasted from the clipboard when a trigger is activated.

Elite: Dangerous supports pasting text into the comms.  This could be useful for pirates, distress signals, or roleplaying.

The first example that comes to mind are pirates.  Pirates need to quickly state their intentions upon pulling a trader out of supercruise.  They then need to provide additional instructions if the initial hold-up is successful (such as telling a giant transport not to point their nose at the pirate to prevent them from simply ramming the pirate to death).

You may already be going this route based on the data tab in the Profile form and the data Action Type.  For programs that do not support use of the clipboard, perhaps fast auto-typing like autohotkey.  Just simply asking for an easier way of dealing with a full string rather than a key sequence.

Loving this program so far!

**Comment by baykovr** [comment]
Thanks.

Interesting idea, I'm working storing data presently. Adding the clipboard functionality wouldn't be too hard, perhaps in the next release if there is time. 

Here's a little sample for your troubles,

![cap](https://cloud.githubusercontent.com/assets/6128886/5778803/7edd4266-9d63-11e4-857a-81bc793e1af4.PNG)

**Comment by AmethystAir** [comment]
I've added a "Type String" action type, where it presses each letter with the specified delay and optionally presses enter at the end of the string. I made it mainly for personal use, but I'd be happy to put the changes up if you want.

**Comment by baykovr** [comment]
Added ability to paste a predefined string into the foreground application, https://github.com/baykovr/AVPI/releases/tag/17.03.15
