### ISSUE TITLE
Gavpi process is not finishing correctly after closing application

### ISSUE THREAD

**Issue by TheTruelycon** [baykovr/AVPI#26]
Severity : Minor

Summary: When user attempts to open Gavpi again after closing the application Gavpi does not open.

Expected result: Please make sure that user is able to open Gavpi at all times

Steps to reproduce:

1) Launch Gavpi
2) Close Gavpi
3) Attempt to open Gavpi again

Observed result: Gavpi is not opening

Repro rate: 100%

Build: 0.04 12.29.14

**Comment by Simon-Dainty** [comment]
Possibly caused by some legacy code for ensuring multiple instances of the
application can't execute.  I'll look into it tonight and strip the
unnecessary code out.

Thanks.

**Comment by baykovr** [comment]
No, he doesn't know about the tray icon, look in your system tray! :)

**Comment by Simon-Dainty** [comment]
That darn tray icon! ;-)  For what it is worth, though, there's a legacy block of code I can shave from GAVPI that isn't needed anymore... :-)

**Comment by TheTruelycon** [comment]
My bad then. Anyways upon right clicking tray icon and selecting EXIT applicatiojn crashes ( microsoft framework error)

**Comment by baykovr** [comment]
Note: I added a bubble text to the tray icon, which should draw the users attention to the fact that gavpi is still running a little better.
