### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by not83** [baykovr/AVPI#28]
You said over 8 months ago on reddit that this would maybe be on Linux.

Any news?

**Comment by baykovr** [comment]
Microsoft did say they are porting .net over to linux, if they port all of the libraries that I use then I will release a linux binary sure.

**Comment by aoighost** [comment]
Just tried to build on OSX and found that Mono does not, in fact, support system.speech.

**Comment by baykovr** [comment]
Which version? I haven't tested it but that link shows its complete.

**Comment by baykovr** [comment]
Confirmed lack of mono support for entire System.Speech namespace. sigh.

**Comment by not83** [comment]
So now what?

**Comment by baykovr** [comment]
I wrongfully assumed that mono would support everything, need a new voice recognition engine in order to support linux.

**Comment by baykovr** [comment]
At this time I cannot support linux pending two major issues:

1. The voice recognition engine is not portable.
2. The input manager is not portable.

If/when these are resolved a port will follow.

**Comment by not83** [comment]
Are these planned to be ported at any point?

**Comment by baykovr** [comment]
At some point yes, I am looking at speech recognition engine alternatives which support Linux.

**Comment by moozaad** [comment]
Did a little light research and this seems like the only current options. Free to use for non-commercial.
http://www.syn.co.in/Syn-Speech.aspx 

http://www.codeproject.com/Articles/890117/Speech-Recognition-in-Mono-and-Net-Csharp


Just system.deployment and inputManager to go.

**Comment by FilBot3** [comment]
> At some point yes, I am looking at speech recognition engine alternatives which support Linux.

So no linux support currently?

**Comment by baykovr** [comment]
Not at this time, but it has been some years since I’ve tried porting. Mono may work.On Jan 19, 2024, at 2:04 PM, FilBot3 ***@***.***> wrote:﻿

At some point yes, I am looking at speech recognition engine alternatives which support Linux.

So no linux support currently?
