### ISSUE TITLE
Bug : InputManager .Net 4.5 conflict

### ISSUE THREAD

**Issue by baykovr** [baykovr/AVPI#29]
VI.cs : load_listen()

"InputManager library, which we rely upon, has issues with .Net 4.5 and throws an Overflow exception.
We'll catch it here and pretty much let it go for now (since Push-to-Talk isn't implemented yet)with the intent of resolving it later."

**Comment by baykovr** [comment]
Can we get away with using 4.0 ... ?

**Comment by Pazns** [comment]
I don't remember writing something about this.

**Comment by baykovr** [comment]
Must of been simon then.

**Comment by Yukinii** [comment]
https://mega.co.nz/#!XoAXXKBZ!1HkwAbIpBM2EBXnw6maltjxlasecBwFvtux8xsnX8Gs
^-- 4.5.2 Inputmanager.dll (breaks keyboard hook)  |  C# Keyboardhook ---v
https://gist.github.com/Yukinii/66239b81f979e2bf3e42

**Comment by AmethystAir** [comment]
I patched the DLL to work with 4.0+ in #50. It was actually a really simple change :)

**Comment by baykovr** [comment]
Open a pr with the new dll, location is in: 

   ` https://github.com/baykovr/AVPI/tree/master/GAVPI/GAVPI/deps/InputManager.dll`

In this way you can receive repository contribution credit. Thanks for the work.

**Comment by baykovr** [comment]
Fixed by @AmethystAir in 3e2c7ae8d09fc1de1f5eca90cffd671dcc93220c
