### ISSUE TITLE
Request for logo

### ISSUE THREAD

**Issue by baykovr** [baykovr/AVPI#30]
If a brave soul wishes to contribute a decent logo, it would be appreciated.

**Comment by Qirion** [comment]
Just an Idea. Will make more logos.

![text3005](https://cloud.githubusercontent.com/assets/4379465/7319039/5c0d88fc-ea68-11e4-9a80-aefa7bdc59d5.png)

**Comment by baykovr** [comment]
That's pretty cool, could you make the letters a bit thinner and crisp?

**Comment by Qirion** [comment]
Will do.

**Comment by baykovr** [comment]
Closing old issue.
