### ISSUE TITLE
Update Key/Mouse Input Implementation

### ISSUE THREAD

**Issue by baykovr** [baykovr/AVPI#35]
The dll we currently use is compiled against .net 3 (or something low like that) which causes problems #29 

We need to abstract keyboard input in order to support linux.

The existing implementation has a few limitations and bugs such as mixed up ordering.

**Comment by baykovr** [comment]
Mainly fixed by #29, closing this issue for now until we run into more serious problems.

**Comment by iNgeon** [comment]
Just a comment\idea, is it not possible to detect window keyboard input and then use https://msdn.microsoft.com/en-us/library/dd375731(v=vs.85).aspx for action sequence key/mouse press translation.

**Comment by baykovr** [comment]
You mean add add the description field?
