### ISSUE TITLE
Not possible to stop sound play actions

### ISSUE THREAD

**Issue by baykovr** [baykovr/AVPI#36]
This is a known bug, since it is not implemented. 

Once a sound file begins playing there is no way to stop it.

**Comment by Kestrelos** [comment]
Think that if you bound a voice command to a multimedia button that you could use the macro to stop the audio? It would be kind of haphazard but still a temp fix

**Comment by baykovr** [comment]
Added an action to stop all playback of audio in 2487c5efe85b8a10be721b1e3c42e7608f6c7f38.
