### ISSUE TITLE
Annoyance : Media Player pop-up confirmation for non-audio files.

### ISSUE THREAD

**Issue by baykovr** [baykovr/AVPI#37]
Windows media player, the underlying lib we are using to play sound files, will make a best effort to play non-audio files. In which case a pop up will appear, possibly tabbing out of the full screen application asking for confirmation. 

Workaround : don't choose non-audio files? This bug is avoidable...

**Comment by baykovr** [comment]
Right, 

Also I think there is a way to check if its valid before trying to play the file, didn't have time with finals going on, however.

**Comment by Kestrelos** [comment]
I'll try to get a bunch of different audio files and see what works and
what doesn't

**Comment by baykovr** [comment]
Thanks,

Anything which windows media can play should work.

**Comment by Kestrelos** [comment]
ah so really i'll just search what is supported, and I'm sure at some point
someone made additional audio codecs for WMP

**Comment by baykovr** [comment]
The file dialog should catch basic file extension selection errors.

If the user selects a non-playable file or the playback fails we simply prompt a warning on failed playback.
