### ISSUE TITLE
Implement support for voice attack profiles

### ISSUE THREAD

**Issue by aoighost** [baykovr/AVPI#39]
The ability to import voice attack profiles would be a good step to allow support for things like the HCS elite dangerous voice packs. I took a look and it appears .vap files are just xml.

**Comment by baykovr** [comment]
Can't support all functions provided by VA yet but this is a good idea. 

I'll mark it for the next phase of the beta after 0.1

**Comment by Drahnier016** [comment]
yeah that would be awesome. im using VA atm. and i cant run it with "dragon speech recognition" so i want to try out your project if it works to import profiles from VA i will download your great work.

Drahnier016

**Comment by baykovr** [comment]
Is there no repository for VA profiles? I am having difficulty finding any online. @Drahnier016 @aoighost if you guys could kindly send me some samples of real use cases (your profiles) I can get a better clue of what features to support.

**Comment by aoighost** [comment]
I'm not sure if I can legally send you it, but the hcs voice packs for
elite dangerous are relatively cheap (10 gbp) and commonly used with voice
attack.

**Comment by baykovr** [comment]
Ah I see the hcs ones include keybindings and audio. (previously I thought they simply provide audio)

**Comment by Stevoni** [comment]
@baykovr The [KICS](http://ripleygalactic.com/kics/) VA profile for Elite: Dangerous is seems to be pretty complex but I haven't dealt with VA a ton.

I'm currently quite busy with work but am interested in implementing VA profile support starting in March or April.

**Comment by baykovr** [comment]
Awesome, looking forward to working together. @Stevoni

**Comment by Stevoni** [comment]
@baykovr I haven't forgotten about working on this. Unfortunately, work has kept me busy, but I will begin researching the file structures soon.

**Comment by baykovr** [comment]
Good to hear.

**Comment by baykovr** [comment]
I think this one is pretty far out on the roadmap, supporting all the functionality of VA is a moving target. If someone is willing to take up the torch will be glad to reopen the issue.
