### ISSUE TITLE
Can't find Controller keys in the Push-to-Talk keys

### ISSUE THREAD

**Issue by tomervutx123** [baykovr/AVPI#41]
I'm looking to assign a key in my Logitech Formula Force EX as a push-to-talk but I can't find it on the list.

**Comment by baykovr** [comment]
So this one is a little tricky since the input key lib used will not explicitly detect the keys. You can try mouse 4 or 5 to see if it works. 

Need to add "press key" functionality to detect to fix this.

**Comment by tomervutx123** [comment]
Will be very helpful if you will add this :)
