### ISSUE TITLE
keypress output sequence mixed up

### ISSUE THREAD

**Issue by 0verclock** [baykovr/AVPI#42]
Hi, I try a simple keypres command to type "push". 
I create action sequence Keypress P, then keypress U, and so on.
I test it using notepad, but the output type getting mixed up, like "phus" or "shup" or "hpus".

Is it just me or anybody else got the same problem? I am using Win7.

Thanks

**Comment by baykovr** [comment]
Without any wait commands its likely outputting too fast for notepad to handle. 

Try adding a small wait in between the presses.

**Comment by 0verclock** [comment]
Well, i did try that but i can only make it work with 100 delay. With 50 delay, the output still mixed up.

However, if i use mouse macro, i can output same sentence much faster to notepad. So i guess there is something other than just delay.

**Comment by baykovr** [comment]
How long are the sequences? I wonder if there is a similar issues with all sequences.

**Comment by 0verclock** [comment]
Like i mention above, only 4 or 5 keypress. You really need to put a long delay between keypress to make it work, so its not practical for gaming.

I test with other voice command app, it can output the same sequence much faster with correct order to notepad.

**Comment by baykovr** [comment]
Thanks for the feedback, I'll try to get this resolved as best as I can.

**Comment by 0verclock** [comment]
Have you been able to recreate the problem? Or it's only happening to me?

**Comment by baykovr** [comment]
So far not able to replicate issue.

**Comment by 0verclock** [comment]
I have try it on different machine, this time I'm using my laptop. The problem still persist.
Both machine (my PC n my laptop) is using Windows 7 64 bit home premium. I have put 10ms delay (see screenshot below) 

![gavpi action sequence](https://cloud.githubusercontent.com/assets/15718152/12837300/ce2e02d2-cbf3-11e5-9d44-2042217d6ffb.png)

but as you can see the output sometimes got mixed up. 
![gavpi mixed up output](https://cloud.githubusercontent.com/assets/15718152/12837304/dbefbeba-cbf3-11e5-82c6-d61211f012b0.png)
If i add the delay to 100ms, it will be always correct, but the typing will be too slow and not practical for gaming.

I am positive the problem is not with the notepad, because i can output longer text to notepad using autohotkey without problem. 
![output to notepad using autohotkey](https://cloud.githubusercontent.com/assets/15718152/12837464/b49fe374-cbf5-11e5-8699-034f62983250.png)

I hope this will help you recreate the problem.

**Comment by baykovr** [comment]
You are running it as administrator right? (just checking)

**Comment by 0verclock** [comment]
Yes, my account is administrator and i have just try it using "running as administrator", and still same problem exist. Nobody ever have same problem with me so far?

**Comment by AmethystAir** [comment]
I'm seeing this same problem. When I sent a sequence of "abcdefg" without delays, here's the result of a few tests:
gdfceba
ecfgdba
dfgceba
dgcbfea
fdgceba
fdgceba
gefdcba
gfdceba
edgcfba
efcgdba

I'll look into this and see what I can find.

**Comment by AmethystAir** [comment]
Alright, this is another problem related to InputManager. InputManager starts a new thread for each "KeyPress" call, meaning it'll be completely out of order for multicore processors. KeyPress can take an array of keys to press, as well as a delay (how long to press each key for), so we'll need to rewrite how key presses are handled. 
It might be useful to have a "string" and "keypress" option; the "string" option could use the multithreaded KeyPress function to send an array of keys to press, and the current "keypress" option could be rewritten to use KeyDown and KeyUp with a "length of press" specified by the user. That should fix the race condition we're seeing here.

**Comment by baykovr** [comment]
Fixed by @AmethystAir in 3e2c7ae8d09fc1de1f5eca90cffd671dcc93220c

**Comment by 0verclock** [comment]
glad somebody able to fix it! thanks AmethystAir! Now just waiting for the release.

**Comment by baykovr** [comment]
Cut release, @0verclock could you validate the fix for us?
https://github.com/baykovr/AVPI/releases/tag/v0.10

**Comment by 0verclock** [comment]
Yes, its working now. It send output keypress much-much faster and sequence is correct even without delay between each keypress. The output is fast enough, much faster than human could type, although not instantaneous. (I can see its output char by char).

Capability to output keypress & string would be perfect, so its easier to implement something like:
Keypress T (teamchat button) + String("Hey I am using AVPI!"). +Keypress Enter.

Is it possible to output string as a whole? something like when you do "copy+paste" a sentence in notepad? It would enable much better "voice command typing" in games. :)

PS>  i get unhandled expection with this release, when you start "listen" then try to close the apps. Need to launch task manager to close it.

**Comment by baykovr** [comment]
Thanks. 

Looking into the crash this morning but cannot replicate so far. (As well as pasting.)

**Comment by 0verclock** [comment]
![image](https://cloud.githubusercontent.com/assets/15718152/14791887/08970cec-0b42-11e6-82a6-49c49c046ce7.png)

![image](https://cloud.githubusercontent.com/assets/15718152/14791907/1a3f6d54-0b42-11e6-9b1b-5c3d45b09b8b.png)

This happened when you try to exit GAVPI from notification area icon when its listening. You need to load profile and issue some command first then exit.

Just forget about the pasting thing.. what i mean is, it still require some time to output a very long keypress sequence (i.e. 1 full sentence). If somehow its possible to output it very fast (like how you can paste a whole paragraph in notepad) it would be better. I know it might not be possible since this app simulate keyboard.
