### ISSUE TITLE
[enhancement] Request Sound Output Device

### ISSUE THREAD

**Issue by KaLam1tyAC** [baykovr/AVPI#43]
I'm not sure how difficult it would be to implement device selection; but at the moment, sound output only goes through the default device. This was one request many people had with VoiceAttack, but due to the base development, implementation would be very difficult.

One thing I'd like to be able to do is, say a command to play a soundfile, and the soundfile outputs to a designated device output (i.e. a secondary soundcard or virtual audio cable, etc., rather than just the default).

Just a thought!
Thanks

**Comment by baykovr** [comment]
Working on it now.

**Comment by baykovr** [comment]
Got it added, however, need to update the profile system to support multi attribute actions. So you cannot actually save/load yet.

3f9caa8313dfe354a059b3c6c3074ec054b83634

**Comment by baykovr** [comment]
Finished in https://github.com/baykovr/AVPI/commit/792e4e69658f1ebeece1976a592bd92df37ea6da

Next release will include feature.
