### ISSUE TITLE
Reordering action bug

### ISSUE THREAD

**Issue by akhahaha** [baykovr/AVPI#44]
Moving an action item up sometimes results in the order being reset. Currently can be worked around by moving other items down instead.

**Comment by baykovr** [comment]
I has able to replicate an issue where moving an item to the top most position (plus one more move up) would put it at end of list.

Is this the issue? Or is the order completely reset in your case?

**Comment by baykovr** [comment]
Fixed, https://github.com/baykovr/AVPI/commit/efc5287c423e7fa5299ddf8530404f1ca1e41b2a

Changes will be reflected in next release.
