### ISSUE TITLE
Push to talk isn't working properly

### ISSUE THREAD

**Issue by AmethystAir** [baykovr/AVPI#50]
I'm running the most recent release (Alpha 0.09) and no matter which key I set the push to talk to, I can't seem to get "Hold" or "PushOnce" to work. Disabling push to talk allows voice recognition to work again.

**Comment by AmethystAir** [comment]
I did some digging and it seems the problem is from the KeyboardHook.InstallHook() call [here](https://github.com/baykovr/AVPI/blob/master/GAVPI/GAVPI/Core/Engine/InputEngine.cs#L108-L110). I'm digging into the InputManager source to see if I can fix it.

**Comment by AmethystAir** [comment]
Here's the fixed DLL. The problem was with the Marshal.GetHINSTANCE call; I believe something changed with how that function works between previous .net versions and 4.0+. Anyway, simply removing that function call and replacing it with '0' in the SetWindowsHookEx fixes the keyboard and mouse hooks.
[InputManager.zip](https://github.com/baykovr/AVPI/files/222477/InputManager.zip)

**Comment by AmethystAir** [comment]
My bad, I just realized this was a duplicate of #29.

**Comment by baykovr** [comment]
Good stuff, thanks.
