### ISSUE TITLE
Rename Project to Auris

### ISSUE THREAD

**Issue by baykovr** [baykovr/AVPI#52]
I have been meaning to rename the project for some time now. The proposal is to refactor the project to a new name of Auris. This repository, and all downloads/releases will continue to be available.

This issue serves as a point for feedback and suggestions.

**Comment by Ozhaaraz** [comment]
I think is much more appealing than AVPI tbh.

**Comment by baykovr** [comment]
I'm going to go ahead and rename + refactor after the next few bug fixes and feature requests are done.
