### ISSUE TITLE
Unhandled exception when adding trigger

### ISSUE THREAD

**Issue by maralg** [baykovr/AVPI#56]
![felmeddelande](https://cloud.githubusercontent.com/assets/7383768/15273407/1e172a46-1a99-11e6-979a-944c50a1d23b.png)

**Comment by baykovr** [comment]
Could not reproduce in latest version, https://github.com/baykovr/AVPI/releases/tag/v0.10. (w/ 0.10.1 patch).

Can you show the version number? (Located in main window 'About' section).

**Comment by baykovr** [comment]
Still cannot reproduce stale issue in 0.10. Closing.
