### ISSUE TITLE
Multiple instances when opening from system tray

### ISSUE THREAD

**Issue by cr0ss0vr** [baykovr/AVPI#58]
Steps to reproduce:

1) open app
2) close app (to minimise it to system tray)
3) double click system tray icon a bunch
4) multiple windows open

weird error that I cant reproduce after doing the above: 
5) select profile
6) start listening
7) close all GAVPI windows (to minimise to system tray)

gave a nasty NPE the first time, not done it since though

**Comment by cr0ss0vr** [comment]
potential fix:

change core/GAVPI.cs OpenMainWindow function to check status of OPEN_LOG_MENU_ITEM

if(sysTrayMenu.MenuItems[OPEN_LOG_MENU_ITEM].Enabled){
//do mainform stuff
}

alternatively have it toggle open on doubleclick

OnDoubleClickIcon(){

if(sysTrayMenu.MenuItems[ OPEN_LOG_MENU_ITEM ].enabled){
    OpenMainWindow( sysTrayMenu.MenuItems[ OPEN_LOG_MENU_ITEM ], null );
}else{

}

**Comment by baykovr** [comment]
Thanks, fixed in commit above.
