### ISSUE TITLE
 Summary feedback AVPI Alpha Build 0.04

### ISSUE THREAD

**Issue by iNgeon** [baykovr/AVPI#6]
*Profile > Modify > Action sequence > New > Action type > KeyDown\KeyUp action's will hold a specific key until an Up or Press action: Doesn`t appear to work. As example, for Star citizen the action sequence is:
 - KeyDown LShiftKey
 - Wait 5000
 - KeyUp LShiftKey
 - Speak Boost

When using notepad, replacing Lshift with Tab is an easy way to test.

*Profile > Modify > Action sequence > New > Action value: Key-bindings confusing, duplicate or missing (examples: LAlt & RAlt & Cursor keys & most special characters like []{};:'",<.>/?/*- cannot easily map)
- Would be awesome if Action Value could jump to\select keyboard button when pressed\mapped by user
- Would also be easier to use actual keyboard keys to manually edit xml profiles

**Comment by baykovr** [comment]
Bizarre, looks like a problem with how we invoke InputManager. This will need some experimentation.

**Comment by baykovr** [comment]
Partly added press support  in https://github.com/baykovr/AVPI/commit/4cc63b0a478c78430ebcaf385d1b22803c8e3539

Closing old issue, if persist will open new ticket for key hold issue.
