### ISSUE TITLE
MP3 Playback Error

### ISSUE THREAD

**Issue by DerScratch** [baykovr/AVPI#61]
When an action sequence containing a mp3 file is triggered, it will play it back the first time, but won't play it back the second time untill you reload the profile. Also, if you choose a output device in the dropdown-window, it will take the device over the device you chose.

**Comment by InacioNeto** [comment]
MP3 files simply don't play on my end.

**Comment by InacioNeto** [comment]
WAV files play once, just like you said.

**Comment by LrdSqrl2507** [comment]
I can confirm the mp3 issue,  plays each file once and not again until listening is disabled and re-enabled. Still trying to solve this issue, has anyone found a format that works properly?

**Comment by baykovr** [comment]
I'm unable to reproduce the issue on my build, can you try out the development build ( https://github.com/baykovr/AVPI/releases/tag/17.03.08 ) to see if the issue persist.

**Comment by iNgeon** [comment]
> I'm unable to reproduce the issue on my build, can you try out the development build ( https://github.com/baykovr/AVPI/releases/tag/17.03.08 ) to see if the issue persist.

On both the last 2 development build version "Listen" does not appear to work for me

**Comment by baykovr** [comment]
Closing this old issue.

Reason: unable to reproduce.
