### ISSUE TITLE
detecting something when mic qui physically off

### ISSUE THREAD

**Issue by Geobert** [baykovr/AVPI#62]
I've let GAVPI run with the mic off from a switch on the headset AND push to talk in toggle mode, OFF position, but I can still see some "?" appear in the logs

using 0.10.1 on Win 10 64bits

**Comment by baykovr** [comment]
The implementation uses windows speech recognition. The "?" gets generated when the engine fails to match on word triggers (i.e. none of the words match).

It is possible to listen on audio out and not only on the mic, could you verify that no other system sound is active while you are tested with the mic off? (For example, music or other people talking causing audio out on the system.)

Ref https://github.com/baykovr/AVPI/blob/master/GAVPI/GAVPI/Core/Engine/InputEngine.cs#L165

**Comment by Geobert** [comment]
I tried with mic off, playing music etc. I must have been mistaken, can't reproduce it
