### ISSUE TITLE
Development Release 17.03.xx Listen & Data

### ISSUE THREAD

**Issue by iNgeon** [baykovr/AVPI#66]
The last 2 development version the data table works better and has all the new features,
but when loading a profile and enabling Listen nothing gets detected.
Also the data table can add new entries but edits cause duplication and the values saved does not update.
At the moment i create in 17.03.15 then launch v0.10 and use the Listen function, but this has its own issues.
I ended up editing the majority of this using notepad++ with the XML plugins
Sample xml : https://pastebin.com/PhEPtnvn

Side note: Also would the form layout like this http://oi64.tinypic.com/bi4jfo.jpg not make more sense perhaps to make editing easier. Find it very tricky jumping back and forth

**Comment by iNgeon** [comment]
Forgot, when adding playsound on an Action sequence,
when using Listen it only plays the track the first time and not again clicking stop and listen again.

**Comment by baykovr** [comment]
Troubleshooting the profile you posted, I found that you have star citizen listed in the associated processes. This will cause triggers only if star citizen is currently in the foreground, removing the association allowed recognition again. ( Tracking in #68 )

**Comment by iNgeon** [comment]
Thanks, not to obvious but quite a silly overlook from my side
