### ISSUE TITLE
Global macros?

### ISSUE THREAD

**Issue by TLCPlusPlus** [baykovr/AVPI#71]
I can see there is a program specific way to do this, but is there a way to do commands globally, like opening a program up?

My current workaround is having cmd.exe targeted to do all the bidding, and that is too much work. 

Just getting to a specific directory (like firefox or chrome to open it up) I have to do
Every. 
Single. 
Keystroke. 
The reason why I have to do this? Because if I do the paste feature, it just does ```^V``` instead.

Some things require me to do ```-skip-uac ``` flag because they will break the macro otherwise since it requires admin privs. (it breaks because of the popup dialogue)

(Simplified) Voiceattack let me do programs by using Lwin key, then typing out the program/command. This worked great because windows 10 store apps dont have a directory, but can be found this way.

**Dont get me wrong. I love this program**, but I have to use VoiceAttack (free version) in tandem with this app just for global commands since I dont like the idea of making a macro that ends up taking up a hour or more of my life to make 1 of, whereas I can do it in 5~ minutes.

**Comment by baykovr** [comment]
If I understand correctly, you want a simple way to launch other programs? 

There is (partial) functionality for this very thing, making arbitrary system calls here:
https://github.com/baykovr/AVPI/blob/master/GAVPI/GAVPI/Core/Engine/Action.cs#L379

I did not have time to implement the GUI component, however it is possible to modify the XML directly as such:

```
<?xml version="1.0" encoding="utf-8"?>
<gavpi>
  <Database />
  <Action_Sequence name="Test" type="Action_Sequence" comment="test" random="False">
	<Action type="ProcessExec" value="notepad.exe" />
  </Action_Sequence>
  <Trigger name="test" value="test" type="Phrase" comment="">
    <Trigger_Event name="Test" type="Action_Sequence" value="" comment="" />
  </Trigger>
</gavpi>
```

An action type "ProcessExec" will execute Process.Start on strings in the value="" field. The sample will open up notepad.exe when you say test. 

Here is a chrome sample:
```
<?xml version="1.0" encoding="utf-8"?>
<gavpi>
  <Database />
  <Action_Sequence name="Test" type="Action_Sequence" comment="test" random="False">
	<Action type="ProcessExec" value="C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" />
  </Action_Sequence>
  <Trigger name="test" value="test" type="Phrase" comment="">
    <Trigger_Event name="Test" type="Action_Sequence" value="" comment="" />
  </Trigger>
</gavpi>
```

**Comment by radamar** [comment]
+1

**Comment by baykovr** [comment]
Will a macro that can execute an arbitrary string work for your use case? 

Example, as configuration it will take a cmd string such as "C:\Program Files\Mozilla Firefox\firefox.exe" (optionally with flags). Then trigger and exec as normal.

**Comment by baykovr** [comment]
@TLCPlusPlus https://github.com/baykovr/AVPI/releases/tag/22.06.28
