### ISSUE TITLE
What speech recognizer engine does this use?

### ISSUE THREAD

**Issue by kevinj2016** [baykovr/AVPI#81]
This is not an issue, but simply a question. What voice recognizer does this tool use, please? Windows Speech Recognizer (WSR)? How good is it at recognizing a whole sentence of words if there is no custom vocabulary feature (for WSR)? Thank you

**Comment by baykovr** [comment]
Correct, the WSR. Without a vocabulary list, I had mixed results. The longer or more complex the sentence the more defects, you'll have to try it out and see.
